"""empty message

Revision ID: 6edb5ed09dcf
Revises: 
Create Date: 2020-12-24 23:56:40.352531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edb5ed09dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='名稱'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB',
        comment='測試table'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
